# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='company name')),
                ('VAT_number', models.CharField(max_length=32, verbose_name='vat number')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=32, verbose_name='invoice id')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='unit cost')),
                ('vat_percent', models.IntegerField(verbose_name='VAT%')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='VAT')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='total')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakturant.ClientCompany')),
            ],
        ),
    ]
