# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoce_type',
            field=models.CharField(default='SI', max_length=2, verbose_name='type'),
            preserve_default=False,
        ),
    ]
