# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakturant', '0002_invoice_invoce_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='VAT_number',
            field=models.CharField(max_length=9, verbose_name='vat number'),
        ),
    ]
