# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakturant', '0003_auto_20170516_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcompany',
            name='giro_account',
            field=models.CharField(default='', max_length=18, verbose_name='giro account'),
            preserve_default=False,
        ),
    ]
