# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakturant', '0005_auto_20170516_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='account',
            field=models.CharField(max_length=20, verbose_name='current account'),
        ),
    ]
