# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakturant', '0008_auto_20170516_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(default='', max_length=10, verbose_name='short name'),
            preserve_default=False,
        ),
    ]
