# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakturant', '0009_company_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='short_name',
            new_name='company_short_name',
        ),
    ]
